version: "3.8"

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

  fastapi:
    build: ./app
    depends_on:
      - mongo
    ports:
      - "8000:8000"
